update LADP_APPLICATION set steppage='/web/home/report.do' where stepname='图表统计';
update LADP_APPLICATION set steppage='/web/home/country.do' where stepname='村镇管理';
update LADP_APPLICATION set steppage='/web/home/level.do' where stepname='等级管理';
update LADP_APPLICATION set steppage='/web/home/part.do' where stepname='考核部门';
update LADP_APPLICATION set steppage='/web/home/person.do' where stepname='人员管理';
update LADP_APPLICATION set steppage='/web/home/record.do' where stepname='考核管理';
update LADP_APPLICATION set steppage='/web/home/statistics.do' where stepname='诚信统计';
update LADP_APPLICATION set steppage='/web/home/log.do' where stepname='日志';
update LADP_APPLICATION set steppage='/web/home/target.do' where stepname='考核指标';
