/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.san.chengxin.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 06-21-2016
 * 
 * XDoclet definition:
 * @struts.form name="addForm"
 */
public class AddForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** target_name property */
	private String target_name;

	/** target_score property */
	private Short target_score;

	/** target_dateline property */
	private Long dateline;

	/** selected_part property */
	private Short part_id;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the target_name.
	 * @return String
	 */
	public String getTarget_name() {
		return target_name;
	}

	/** 
	 * Set the target_name.
	 * @param target_name The target_name to set
	 */
	public void setTarget_name(String target_name) {
		this.target_name = target_name;
	}

	/** 
	 * Returns the target_score.
	 * @return String
	 */
	public Short getTarget_score() {
		return target_score;
	}

	/** 
	 * Set the target_score.
	 * @param target_score The target_score to set
	 */
	public void setTarget_score(Short target_score) {
		this.target_score = target_score;
	}

	/** 
	 * Returns the target_dateline.
	 * @return String
	 */
	public Long getDateline() {
		return dateline;
	}

	/** 
	 * Set the target_dateline.
	 * @param target_dateline The target_dateline to set
	 */
	public void setDateline(Long dateline) {
		this.dateline = dateline;
	}

	/** 
	 * Returns the selected_part.
	 * @return String
	 */
	public Short getPart_id() {
		return part_id;
	}

	/** 
	 * Set the selected_part.
	 * @param selected_part The selected_part to set
	 */
	public void setPart_id(Short part_id) {
		this.part_id = part_id;
	}
}