package com.san.mxchengxin.form.record;
/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 06-28-2016
 * 
 * XDoclet definition:
 * @struts.form name="CountryForm"
 */
public class RecordForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private String truename;
	private String ssid;
	private Short country_id;
	private Short target_id;
	
	/*
	 * Generated Methods
	 */

	public String getTruename() {
		return truename;
	}

	public void setTruename(String truename) {
		this.truename = truename;
	}

	public String getSsid() {
		return ssid;
	}

	public void setSsid(String ssid) {
		this.ssid = ssid;
	}

	public Short getCountry_id() {
		return country_id;
	}

	public void setCountry_id(Short country_id) {
		this.country_id = country_id;
	}

	public Short getTarget_id() {
		return target_id;
	}

	public void setTarget_id(Short target_id) {
		this.target_id = target_id;
	}

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

}