package com.san.mxchengxin.form.record;
/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 06-28-2016
 * 
 * XDoclet definition:
 * @struts.form name="RecordAddForm"
 */
public class RecordAddForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/** country_phone property */
	private String country_phone;

	/** country_contact property */
	private String country_contact;

	/** country_display_order property */
	private String country_display_order;

	/** country_name property */
	private String country_name;

	/** parent_id property */
	private Short parent_id;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the country_phone.
	 * @return String
	 */
	public String getCountry_phone() {
		return country_phone;
	}

	/** 
	 * Set the country_phone.
	 * @param country_phone The country_phone to set
	 */
	public void setCountry_phone(String country_phone) {
		this.country_phone = country_phone;
	}

	/** 
	 * Returns the country_contact.
	 * @return String
	 */
	public String getCountry_contact() {
		return country_contact;
	}

	/** 
	 * Set the country_contact.
	 * @param country_contact The country_contact to set
	 */
	public void setCountry_contact(String country_contact) {
		this.country_contact = country_contact;
	}

	/** 
	 * Returns the country_display_order.
	 * @return String
	 */
	public String getCountry_display_order() {
		return country_display_order;
	}

	/** 
	 * Set the country_display_order.
	 * @param country_display_order The country_display_order to set
	 */
	public void setCountry_display_order(String country_display_order) {
		this.country_display_order = country_display_order;
	}

	/** 
	 * Returns the country_name.
	 * @return String
	 */
	public String getCountry_name() {
		return country_name;
	}

	/** 
	 * Set the country_name.
	 * @param country_name The country_name to set
	 */
	public void setCountry_name(String country_name) {
		this.country_name = country_name;
	}

	/** 
	 * Returns the parent_id.
	 * @return Short
	 */
	public Short getParent_id() {
		return parent_id;
	}

	/** 
	 * Set the parent_id.
	 * @param parent_id The parent_id to set
	 */
	public void setParent_id(Short parent_id) {
		this.parent_id = parent_id;
	}
}