package com.san.mhcx.uploadlogs.model;

/**
 * TUploadErrorLogs generated by MyEclipse Persistence Tools
 */

public class TUploadErrorLogs implements java.io.Serializable {

	// Fields

	private String logErrorId;
	private String logNumber;
	private Integer logErrorLinenum;
	private String logErrorInfo;

	// Constructors

	/** default constructor */
	public TUploadErrorLogs() {
	}

	/** minimal constructor */
	public TUploadErrorLogs(String logErrorId) {
		this.logErrorId = logErrorId;
	}

	/** full constructor */
	public TUploadErrorLogs(String logErrorId, String logNumber,
			Integer logErrorLinenum, String logErrorInfo) {
		this.logErrorId = logErrorId;
		this.logNumber = logNumber;
		this.logErrorLinenum = logErrorLinenum;
		this.logErrorInfo = logErrorInfo;
	}

	// Property accessors

	public String getLogErrorId() {
		return this.logErrorId;
	}

	public void setLogErrorId(String logErrorId) {
		this.logErrorId = logErrorId;
	}

	public String getLogNumber() {
		return this.logNumber;
	}

	public void setLogNumber(String logNumber) {
		this.logNumber = logNumber;
	}

	public Integer getLogErrorLinenum() {
		return this.logErrorLinenum;
	}

	public void setLogErrorLinenum(Integer logErrorLinenum) {
		this.logErrorLinenum = logErrorLinenum;
	}

	public String getLogErrorInfo() {
		return this.logErrorInfo;
	}

	public void setLogErrorInfo(String logErrorInfo) {
		this.logErrorInfo = logErrorInfo;
	}

}