package com.san.mhcx.uploadlogs.model;

import java.util.Date;

/**
 * TUploadLogs generated by MyEclipse Persistence Tools
 */

public class TUploadLogs implements java.io.Serializable {

	// Fields

	private String logId;
	private String logUser;
	private Date logTime;
	private String logTableId;
	private Integer logSunSize;
	private Integer logReplaySize;
	private Integer logUploadSize;
	private Integer logFailSize;
	private Integer bdcgs;
	private Integer bdsbs;
	private String logStates;
	private String remark;
	private String remark2;

	// Constructors

	public String getRemark2() {
		return remark2;
	}

	public void setRemark2(String remark2) {
		this.remark2 = remark2;
	}

	/** default constructor */
	public TUploadLogs() {
	}

	/** minimal constructor */
	public TUploadLogs(String logId) {
		this.logId = logId;
	}

	/** full constructor */
	public TUploadLogs(String logId, String logUser, Date logTime,
			String logTableId, Integer logSunSize, Integer logReplaySize,
			Integer logUploadSize, Integer logFailSize, String logStates,String remark,String remark2,Integer bdcgs,Integer bdsbs) {
		this.logId = logId;
		this.logUser = logUser;
		this.logTime = logTime;
		this.logTableId = logTableId;
		this.logSunSize = logSunSize;
		this.logReplaySize = logReplaySize;
		this.logUploadSize = logUploadSize;
		this.logFailSize = logFailSize;
		this.logStates = logStates;
		this.remark = remark;
		this.remark2 = remark2;
		this.bdcgs = bdcgs;
		this.bdsbs = bdsbs;
	}

	// Property accessors

	public String getLogId() {
		return this.logId;
	}

	public void setLogId(String logId) {
		this.logId = logId;
	}

	public String getLogUser() {
		return this.logUser;
	}

	public void setLogUser(String logUser) {
		this.logUser = logUser;
	}

	public Date getLogTime() {
		return this.logTime;
	}

	public void setLogTime(Date logTime) {
		this.logTime = logTime;
	}

	public String getLogTableId() {
		return this.logTableId;
	}

	public void setLogTableId(String logTableId) {
		this.logTableId = logTableId;
	}

	public Integer getLogSunSize() {
		return this.logSunSize;
	}

	public void setLogSunSize(Integer logSunSize) {
		this.logSunSize = logSunSize;
	}

	public Integer getLogReplaySize() {
		return this.logReplaySize;
	}

	public void setLogReplaySize(Integer logReplaySize) {
		this.logReplaySize = logReplaySize;
	}

	public Integer getLogUploadSize() {
		return this.logUploadSize;
	}

	public void setLogUploadSize(Integer logUploadSize) {
		this.logUploadSize = logUploadSize;
	}

	public Integer getLogFailSize() {
		return this.logFailSize;
	}

	public void setLogFailSize(Integer logFailSize) {
		this.logFailSize = logFailSize;
	}

	public String getLogStates() {
		return this.logStates;
	}

	public void setLogStates(String logStates) {
		this.logStates = logStates;
	}

	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Integer getBdcgs() {
		return bdcgs;
	}

	public void setBdcgs(Integer bdcgs) {
		this.bdcgs = bdcgs;
	}

	public Integer getBdsbs() {
		return bdsbs;
	}

	public void setBdsbs(Integer bdsbs) {
		this.bdsbs = bdsbs;
	}

}