package com.san.mhcx.uploadlogs.model;

import java.util.Date;

/**
 * VUploadLogs generated by MyEclipse Persistence Tools
 */

public class VUploadLogs implements java.io.Serializable {

	// Fields

	private String logId;
	private String logUser;
	private Date logTime;
	private String tableNameCn;
	private String tableId;
	private String ouname;
	private String ouid;
	private Integer logSunSize;
	private Integer logReplaySize;
	private Integer logUploadSize;
	private Integer logFailSize;
	private String logStates;

	// Constructors

	public VUploadLogs() {
	}
	
	/** minimal constructor */
	public VUploadLogs(String logId) {
		this.logId = logId;
	}
	/** full constructor */
	public VUploadLogs(String logId, String logUser, Date logTime,
			String tableNameCn, String tableId, String ouname, String ouid,
			Integer logSunSize, Integer logReplaySize, Integer logUploadSize,
			Integer logFailSize, String logStates) {
		this.logId = logId;
		this.logUser = logUser;
		this.logTime = logTime;
		this.tableNameCn = tableNameCn;
		this.tableId = tableId;
		this.ouname = ouname;
		this.ouid = ouid;
		this.logSunSize = logSunSize;
		this.logReplaySize = logReplaySize;
		this.logUploadSize = logUploadSize;
		this.logFailSize = logFailSize;
		this.logStates = logStates;
	}


	public String getLogId() {
		return logId;
	}


	public void setLogId(String logId) {
		this.logId = logId;
	}


	public String getLogUser() {
		return logUser;
	}


	public void setLogUser(String logUser) {
		this.logUser = logUser;
	}


	public Date getLogTime() {
		return logTime;
	}


	public void setLogTime(Date logTime) {
		this.logTime = logTime;
	}


	public String getTableNameCn() {
		return tableNameCn;
	}


	public void setTableNameCn(String tableNameCn) {
		this.tableNameCn = tableNameCn;
	}


	public String getTableId() {
		return tableId;
	}


	public void setTableId(String tableId) {
		this.tableId = tableId;
	}


	public String getOuname() {
		return ouname;
	}


	public void setOuname(String ouname) {
		this.ouname = ouname;
	}


	public String getOuid() {
		return ouid;
	}


	public void setOuid(String ouid) {
		this.ouid = ouid;
	}


	public Integer getLogSunSize() {
		return logSunSize;
	}


	public void setLogSunSize(Integer logSunSize) {
		this.logSunSize = logSunSize;
	}


	public Integer getLogReplaySize() {
		return logReplaySize;
	}


	public void setLogReplaySize(Integer logReplaySize) {
		this.logReplaySize = logReplaySize;
	}


	public Integer getLogUploadSize() {
		return logUploadSize;
	}


	public void setLogUploadSize(Integer logUploadSize) {
		this.logUploadSize = logUploadSize;
	}


	public Integer getLogFailSize() {
		return logFailSize;
	}


	public void setLogFailSize(Integer logFailSize) {
		this.logFailSize = logFailSize;
	}


	public String getLogStates() {
		return logStates;
	}


	public void setLogStates(String logStates) {
		this.logStates = logStates;
	}

}