/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.san.mxchengxin.form.country;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 06-26-2016
 * 
 * XDoclet definition:
 * @struts.form name="CountryForm"
 */
public class CountryForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** countrySelect property */
	private String countrySelect;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the countrySelect.
	 * @return String
	 */
	public String getCountrySelect() {
		return countrySelect;
	}

	/** 
	 * Set the countrySelect.
	 * @param countrySelect The countrySelect to set
	 */
	public void setCountrySelect(String countrySelect) {
		this.countrySelect = countrySelect;
	}
}