package com.san.ysjgl.model;

/**
 * CodeTable generated by MyEclipse Persistence Tools
 */

public class CodeTable implements java.io.Serializable {

	// Fields

	private String id;
	private String code;
	private String codeType;
	private String description;
	private String sourceTable;
	private String parentId;
	private String isTop;
	private String codeTypeName;
	private String feild1;
	private String feild2;
	private String feild3;

	// Constructors

	/** default constructor */
	public CodeTable() {
	}

	/** minimal constructor */
	public CodeTable(String id) {
		this.id = id;
	}

	/** full constructor */
	public CodeTable(String id, String code, String codeType,
			String description, String sourceTable, String parentId,
			String isTop, String codeTypeName, String feild1, String feild2,
			String feild3) {
		this.id = id;
		this.code = code;
		this.codeType = codeType;
		this.description = description;
		this.sourceTable = sourceTable;
		this.parentId = parentId;
		this.isTop = isTop;
		this.codeTypeName = codeTypeName;
		this.feild1 = feild1;
		this.feild2 = feild2;
		this.feild3 = feild3;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getCodeType() {
		return this.codeType;
	}

	public void setCodeType(String codeType) {
		this.codeType = codeType;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getSourceTable() {
		return this.sourceTable;
	}

	public void setSourceTable(String sourceTable) {
		this.sourceTable = sourceTable;
	}

	public String getParentId() {
		return this.parentId;
	}

	public void setParentId(String parentId) {
		this.parentId = parentId;
	}

	public String getIsTop() {
		return this.isTop;
	}

	public void setIsTop(String isTop) {
		this.isTop = isTop;
	}

	public String getCodeTypeName() {
		return this.codeTypeName;
	}

	public void setCodeTypeName(String codeTypeName) {
		this.codeTypeName = codeTypeName;
	}

	public String getFeild1() {
		return this.feild1;
	}

	public void setFeild1(String feild1) {
		this.feild1 = feild1;
	}

	public String getFeild2() {
		return this.feild2;
	}

	public void setFeild2(String feild2) {
		this.feild2 = feild2;
	}

	public String getFeild3() {
		return this.feild3;
	}

	public void setFeild3(String feild3) {
		this.feild3 = feild3;
	}

}