/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.san.mxchengxin.form.level;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 06-20-2016
 * 
 * XDoclet definition:
 * @struts.form name="LevelForm"
 */
public class LevelForm extends ActionForm {
	/*
	 * Generated fields
	 */
	/** target_name property */
	private String level_name;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the target_name.
	 * @return String
	 */
	public String getlevel_name() {
		return level_name;
	}

	/** 
	 * Set the level_name.
	 * @param level_name The target_name to set
	 */
	public void setlevel_name(String level_name) {
		this.level_name = level_name;
	}
}