package com.san.mhcx.mkdz.model;

import java.util.Date;

/**
 * TUploadLogs generated by MyEclipse Persistence Tools
 */

public class TMkdzInfo implements java.io.Serializable {

	// Fields

	private String mkId;
	private String mkName;
	private String jflx;
	private Integer jfsc;
	private Integer jf;
	private String zt;
	private String jfsclx;
	
	
	public TMkdzInfo() {
	}
	public TMkdzInfo(String mkId) {
		this.mkId = mkId;
	}
	public TMkdzInfo(String mkId, String mkName, String jflx,
			Integer jfsc, Integer jf,String zt,String jfsclx) {
		this.mkId = mkId;
		this.mkName = mkName;
		this.jflx = jflx;
		this.jfsc = jfsc;
		this.jf = jf;
		this.zt= zt;
		this.jfsclx= jfsclx;
	}
	
	public String getMkId() {
		return mkId;
	}
	public void setMkId(String mkId) {
		this.mkId = mkId;
	}
	public String getMkName() {
		return mkName;
	}
	public void setMkName(String mkName) {
		this.mkName = mkName;
	}
	public String getJflx() {
		return jflx;
	}
	public void setJflx(String jflx) {
		this.jflx = jflx;
	}
	public Integer getJfsc() {
		return jfsc;
	}
	public void setJfsc(Integer jfsc) {
		this.jfsc = jfsc;
	}
	public Integer getJf() {
		return jf;
	}
	public void setJf(Integer jf) {
		this.jf = jf;
	}
	public String getZt() {
		return zt;
	}
	public void setZt(String zt) {
		this.zt = zt;
	}
	public String getJfsclx() {
		return jfsclx;
	}
	public void setJfsclx(String jfsclx) {
		this.jfsclx = jfsclx;
	}
	

	// Constructors

	

}