package com.san.mxchengxin.form.part;
/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 06-28-2016
 * 
 * XDoclet definition:
 * @struts.form name="CtyAddForm"
 */
public class PartAddForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** part name property */
	private String part_name;



	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the part_name.
	 * @return String
	 */
	public String getpart_name() {
		return part_name;
	}

	/** 
	 * Set the part_name.
	 * @param part_name The country_phone to set
	 */
	public void setpart_name(String part_name) {
		this.part_name = part_name;
	}

}