/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.san.mxchengxin.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 06-20-2016
 * 
 * XDoclet definition:
 * @struts.form name="targetForm"
 */
public class TargetForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** part_id property */
	private Integer part_id;

	/** target_name property */
	private String target_name;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the part_id.
	 * @return Integer
	 */
	public Integer getPart_id() {
		return part_id;
	}

	/** 
	 * Set the part_id.
	 * @param part_id The part_id to set
	 */
	public void setPart_id(Integer part_id) {
		this.part_id = part_id;
	}

	/** 
	 * Returns the target_name.
	 * @return String
	 */
	public String getTarget_name() {
		return target_name;
	}

	/** 
	 * Set the target_name.
	 * @param target_name The target_name to set
	 */
	public void setTarget_name(String target_name) {
		this.target_name = target_name;
	}
}