/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import com.yourcompany.struts.form.TargetForm;
import com.login.UserDAO;

public class TargetAction extends Action {
	private UserDAO userDAO;
	
	public UserDAO getUserDAO() {
		return userDAO;
	}
	
	public void setUserDAO(UserDAO userDAO) {
		this.userDAO = userDAO;
	}
	
	public ActionForward execute(ActionMapping mapping, ActionForm form,
		HttpServletRequest request, HttpServletResponse response) {
		
		//return mapping.findForward( "indexForword" );
		
		TargetForm loginForm = (TargetForm) form;
		String username=loginForm.getUsername();
		String password=loginForm.getPassword();
		
		if( userDAO.isValidUser( username, password ) ){
			return mapping.findForward( "indexForword" );
		}else{
			return mapping.getInputForward();
		}
		
	}
}
