/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.san.mxchengxin.form.statistics;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 07-11-2016
 * 
 * XDoclet definition:
 * @struts.form name="StatisticsForm"
 */
public class StatisticsForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** catSelect property */
	private Integer catSelect;

	/** levelSelect property */
	private Integer levelSelect;

	


	public Integer getCatSelect() {
		return catSelect;
	}

	public void setCatSelect(Integer catSelect) {
		this.catSelect = catSelect;
	}

	public Integer getLevelSelect() {
		return levelSelect;
	}

	public void setLevelSelect(Integer levelSelect) {
		this.levelSelect = levelSelect;
	}

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	
}